#ifndef OP_CODES_H_
#define OP_CODES_H_

typedef enum
{
	MENSAJE,
	PAQUETE,
	HANDSHAKE,
	CREAR_PROCESO_EN_MEMORIA,
	LIBERAR_PROCESO_EN_MEMORIA,
	DISPATCH_PROCESO,
	FETCH_INSTRUCCION,
	REDIMENSIONAR_MEMORIA_PROCESO,
	ESCRIBIR_DATO_EN_MEMORIA,
	LEER_DATO_DE_MEMORIA,
	DATO_LEIDO_DE_MEMORIA,
	CONSULTAR_TABLA_DE_PAGINAS,
	RESPUESTA,
	INTERRUPCION_USUARIO,
	INTERRUPCION_QUANTUM,
	PROCESO_TERMINADO,
	PROCESO_BLOQUEADO_IO,
	PROCESO_SOLICITA_RECURSO,
	PROCESO_LIBERA_RECURSO,
	PROCESO_DESALOJADO,
	ERROR_DE_PROCESAMIENTO,
	EJECUTAR_INSTRUCCION_IO,
	FIN_EJECUCION_IO,
	CREAR_ARCHIVO_FS,
	TRUNCAR_ARCHIVO_FS,
	ELIMINAR_ARCHIVO_FS,
	SUCCESS,
	OUT_OF_MEMORY
} op_code;

#define ERROR -1

const char *traduce_cod_op(op_code code);

#endif